name: Python CI/CD

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Choose the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python-art.py # Replace 'your_script.py' with the name of your Python script
